#target photoshop
/* MugX CEP host: uses the existing repository assets/ layout. */
var MugX=MugX||{};MugX.state=MugX.state||{project:null,assets:null,photos:null,photoFolder:null,mirror:true};
MugX._json=function(x){try{return JSON.stringify(x);}catch(e){return '{"ok":false,"message":"Response encoding failed."}';}};MugX._ok=function(m,x){var r={ok:true,message:m};if(x)for(var k in x)r[k]=x[k];return MugX._json(r);};MugX._fail=function(m){return MugX._json({ok:false,message:m});};MugX._args=function(s){try{return s?JSON.parse(s):{};}catch(e){return{};}};MugX._doc=function(){return app.documents.length?app.activeDocument:null;};
MugX._folder=function(path){var f=new Folder(path);return f.exists?f:null;};MugX._join=function(base,name){return new Folder(base.fsName+'/'+name);};MugX._kids=function(f){if(!f||!f.exists)return[];return f.getFiles(function(x){return x instanceof Folder;});};MugX._child=function(f,name){var a=MugX._kids(f);for(var i=0;i<a.length;i++)if(a[i].name.toLowerCase()===name.toLowerCase())return a[i];return null;};MugX._walk=function(folder,test,out){out=out||[];if(!folder||!folder.exists)return out;var a=folder.getFiles();for(var i=0;i<a.length;i++){if(a[i] instanceof Folder)MugX._walk(a[i],test,out);else if(test(a[i]))out.push(a[i]);}return out;};MugX._sort=function(a){a.sort(function(x,y){var p=x.name.toLowerCase(),q=y.name.toLowerCase(),m=p.match(/^(\d+)/),n=q.match(/^(\d+)/);if(m&&n&&Number(m[1])!==Number(n[1]))return Number(m[1])-Number(n[1]);return p<q?-1:p>q?1:0;});return a;};MugX._image=function(f){return /\.(jpg|jpeg|png|tif|tiff)$/i.test(f.name);};MugX._psd=function(f){return /\.psd$/i.test(f.name);};
MugX._setProject=function(root){var assets=MugX._child(root,'assets');if(!assets)return false;MugX.state.project=root;MugX.state.assets=assets;var sample=MugX._child(assets,'sample_data');if(sample)MugX.state.photoFolder=sample;return true;};
MugX.detectRepositoryAssets=function(){try{var here=new File($.fileName).parent;var extension=here.parent;var project=extension.parent;var assets=MugX._child(project,'assets');if(!assets)return MugX._fail('Repository assets were not found beside photoshop-extension. Click Select Project Folder and choose your mugxplugin folder.');MugX._setProject(project);return MugX._ok('Detected repository assets.',{root:project.fsName,assets:assets.fsName});}catch(e){return MugX._fail('Asset detection failed: '+e.message);}};
MugX.chooseProjectRoot=function(){try{var root=Folder.selectDialog('Choose the mugxplugin project folder (it must contain assets/)');if(!root)return MugX._ok('Project selection cancelled.');if(!MugX._setProject(root))return MugX._fail('The selected folder has no assets/ directory. Choose the mugxplugin project folder shown in Finder.');return MugX._ok('Repository project selected.',{root:root.fsName,assets:MugX.state.assets.fsName});}catch(e){return MugX._fail('Project selection failed: '+e.message);}};
MugX._photos=function(){var f=MugX.state.photoFolder;if(!f&&MugX.state.assets)f=MugX._child(MugX.state.assets,'sample_data');if(!f)return[];MugX.state.photoFolder=f;MugX.state.photos=MugX._sort(MugX._walk(f,MugX._image));return MugX.state.photos;};
MugX.choosePhotoFolder=function(){try{var f=Folder.selectDialog('Choose the customer photo folder');if(!f)return MugX._ok('Customer photo folder selection cancelled.');MugX.state.photoFolder=f;var p=MugX._photos();return MugX._ok(p.length+' supported photo(s) loaded.',{count:p.length,folder:f.fsName});}catch(e){return MugX._fail('Could not select customer photos: '+e.message);}};
MugX.refreshPhotos=function(){try{var p=MugX._photos();return MugX._ok(p.length+' supported photo(s) loaded in numeric-then-name order.',{count:p.length,folder:MugX.state.photoFolder?MugX.state.photoFolder.fsName:''});}catch(e){return MugX._fail('Photo refresh failed: '+e.message);}};
MugX.openPhoto=function(){try{var f=File.openDialog('Open customer photo','*.jpg;*.jpeg;*.png;*.tif;*.tiff');if(!f)return MugX._ok('Open Photo cancelled.');app.open(f);return MugX._ok('Opened '+f.name+'.');}catch(e){return MugX._fail('Open Photo failed: '+e.message);}};
MugX._slots=function(d){var a=[],all=[];function walk(p){for(var i=0;i<p.layers.length;i++){var l=p.layers[i];all.push(l);if(l.typename==='LayerSet')walk(l);}}walk(d);for(var j=0;j<all.length;j++)if(/^Photo_\d+$/i.test(all[j].name))a.push(all[j]);a.sort(function(x,y){return parseInt(x.name.match(/\d+/)[0],10)-parseInt(y.name.match(/\d+/)[0],10);});return a;};
MugX._pick=function(label,files){if(!files.length)return null;if(files.length===1)return files[0];var s='Choose '+label+':\n';for(var i=0;i<files.length;i++)s+=(i+1)+'. '+files[i].name+'\n';var n=prompt(s,'1');if(n===null)return null;n=parseInt(n,10)-1;return n>=0&&n<files.length?files[n]:null;};
MugX.openPSD=function(raw){try{var a=MugX._args(raw),product=a.product==='bottle'?'bottle':'mug',count=parseInt(a.count,10)||0,dir=MugX.state.assets?MugX._child(MugX.state.assets,'templates'):null,files=dir?MugX._sort(MugX._walk(dir,MugX._psd)):[];var filtered=[];for(var i=0;i<files.length;i++){var key=(files[i].fsName+' '+files[i].name).toLowerCase();if((!product||key.indexOf(product)>=0)&&(!count||key.indexOf(String(count))>=0||key.indexOf(count+'photo')>=0))filtered.push(files[i]);}if(filtered.length)files=filtered;var f=MugX._pick(product+(count?' '+count+' photo':'')+' template',files);if(!f)f=File.openDialog('Choose '+product+' PSD from assets/templates','*.psd');if(!f)return MugX._ok('Open PSD cancelled. Add PSD files under assets/templates or select one manually.');app.open(f);var slots=MugX._slots(app.activeDocument);return MugX._ok('Opened '+f.name+'. Found '+slots.length+' Photo_XX target(s).',{slots:slots.length,folder:dir?dir.fsName:''});}catch(e){return MugX._fail('Open PSD failed: '+e.message);}};
MugX.validateTemplate=function(){try{var d=MugX._doc();if(!d)return MugX._fail('Open a PSD template first.');var s=MugX._slots(d);if(!s.length)return MugX._fail('No Photo_XX targets found. Name smart-object layers Photo_01, Photo_02, etc.');for(var i=0;i<s.length;i++)if(s[i].kind!==LayerKind.SMARTOBJECT)return MugX._fail(s[i].name+' must be a Smart Object.');return MugX._ok('Template valid: '+s.length+' Smart Object slot(s).',{slots:s.length});}catch(e){return MugX._fail('Template validation failed: '+e.message);}};
MugX._replace=function(l,f){app.activeDocument.activeLayer=l;var d=new ActionDescriptor();d.putPath(charIDToTypeID('null'),f);executeAction(stringIDToTypeID('placedLayerReplaceContents'),d,DialogModes.NO);};MugX.autoFill=function(raw){try{var d=MugX._doc();if(!d)return MugX._fail('Open a PSD before Auto Fill.');var p=MugX._photos(),s=MugX._slots(d),a=MugX._args(raw),wanted=parseInt(a.count,10)||s.length;if(!p.length)return MugX._fail('No customer photos. Click Choose Customer Photo Folder.');if(!s.length)return MugX._fail('No Photo_XX smart-object slots. Click Validate Photo_XX Slots.');var n=Math.min(wanted,p.length,s.length);for(var i=0;i<n;i++)MugX._replace(s[i],p[i]);return MugX._ok('Complete! '+n+' image(s) placed sequentially.'+(p.length>n?' '+(p.length-n)+' unused.':'')+(s.length>n?' '+(s.length-n)+' slots unchanged.':''),{placed:n,available:p.length,slots:s.length});}catch(e){return MugX._fail('Auto Fill failed: '+e.message);}};
MugX.autoCorrect=function(){try{var d=MugX._doc();if(!d)return MugX._fail('Open an image and select an editable raster layer.');var l=d.activeLayer;if(l.typename!=='ArtLayer'||l.kind===LayerKind.SMARTOBJECT)return MugX._fail('Select a raster photo layer. To edit a smart object, open it first.');try{l.autoLevels();}catch(x){}try{l.autoContrast();}catch(y){}try{l.autoColor();}catch(z){}return MugX._ok('Auto correction applied.');}catch(e){return MugX._fail('Auto correction failed: '+e.message);}};
MugX.smooth=function(){try{var d=MugX._doc();if(!d)return MugX._fail('Open an image and select an editable raster layer.');var l=d.activeLayer;if(l.typename!=='ArtLayer'||l.kind===LayerKind.SMARTOBJECT)return MugX._fail('Select a raster photo layer. To smooth a smart object, open it first.');l.applyGaussianBlur(1.2);return MugX._ok('Smooth applied.');}catch(e){return MugX._fail('Smooth failed: '+e.message);}};
MugX.resizeSelected=function(){try{if(!MugX._doc())return MugX._fail('Open a design first.');executeAction(stringIDToTypeID('freeTransform'),undefined,DialogModes.ALL);return MugX._ok('Free Transform started.');}catch(e){return MugX._fail('Resize failed: '+e.message);}};
MugX._asset=function(names,pat,label){var d=null;if(MugX.state.assets)for(var i=0;i<names.length&&!d;i++)d=MugX._child(MugX.state.assets,names[i]);var fs=d?MugX._sort(MugX._walk(d,function(f){return pat.test(f.name);})):[];var f=MugX._pick(label,fs);return f||File.openDialog('Choose '+label,'*.jpg;*.jpeg;*.png;*.psd');};
MugX.changeBackground=function(){try{var d=MugX._doc();if(!d)return MugX._fail('Open a design first.');var f=MugX._asset(['backgrounds'],/\.(jpg|jpeg|png|tif|tiff)$/i,'background');if(!f)return MugX._ok('Background selection cancelled.');var all=[];function w(p){for(var i=0;i<p.layers.length;i++){all.push(p.layers[i]);if(p.layers[i].typename==='LayerSet')w(p.layers[i]);}}w(d);for(var j=0;j<all.length;j++)if(/^Background$/i.test(all[j].name)){if(all[j].kind!==LayerKind.SMARTOBJECT)return MugX._fail('Background layer must be a Smart Object.');MugX._replace(all[j],f);return MugX._ok('Background replaced.');}return MugX._fail('No smart-object layer named Background found.');}catch(e){return MugX._fail('Background failed: '+e.message);}};
MugX.addElement=function(){try{var f=MugX._asset(['effects','text_presets','collage_themes'],/\.(jpg|jpeg|png|psd)$/i,'effect, text preset, or element');if(!f)return MugX._ok('Element selection cancelled.');app.open(f);return MugX._ok('Opened '+f.name+'. Copy its layer into the design, then transform it.');}catch(e){return MugX._fail('Add Element failed: '+e.message);}};
MugX.changePageSize=function(){try{var d=MugX._doc();if(!d)return MugX._fail('Open a design first.');var w=prompt('Width in inches',String(d.width.as('in')));if(w===null)return MugX._ok('Page size cancelled.');var h=prompt('Height in inches',String(d.height.as('in')));if(h===null)return MugX._ok('Page size cancelled.');d.resizeImage(UnitValue(Number(w),'in'),UnitValue(Number(h),'in'),250,ResampleMethod.BICUBIC);return MugX._ok('Page set to '+w+' × '+h+' in at 250 DPI.');}catch(e){return MugX._fail('Page size failed: '+e.message);}};
MugX.swapSelected=function(){return MugX._fail('Photo Swap requires two selected Photo_XX layers. Photoshop CEP does not reliably expose multi-layer selection; swap smart-object contents manually for this template.');};MugX.saveMaster=function(){try{var d=MugX._doc();if(!d)return MugX._fail('Open a design first.');if(d.saved)d.save();else{var f=File.saveDialog('Save master PSD','*.psd');if(!f)return MugX._ok('Save cancelled.');d.saveAs(f,new PhotoshopSaveOptions(),true,Extension.LOWERCASE);}return MugX._ok('Master PSD saved.');}catch(e){return MugX._fail('Save failed: '+e.message);}};
MugX.createMockup=function(){try{var f=MugX._asset(['mockups'],/\.psd$/i,'mockup PSD');if(!f)return MugX._ok('Mockup selection cancelled.');app.open(f);return MugX._ok('Opened '+f.name+'. Replace its DESIGN smart object, then export JPG.');}catch(e){return MugX._fail('Mockup failed: '+e.message);}};MugX.preparePrint=function(){try{var d=MugX._doc();if(!d)return MugX._fail('Open a finished design first.');var p=d.duplicate(d.name.replace(/\.psd$/i,'')+'_PRINT',false);if(MugX.state.mirror)try{p.activeLayer.resize(-100,100,AnchorPosition.MIDDLECENTER);}catch(x){}return MugX._ok('Created print copy. Mirror is '+(MugX.state.mirror?'enabled':'disabled')+'.');}catch(e){return MugX._fail('Prepare print failed: '+e.message);}};MugX.toggleMirror=function(){MugX.state.mirror=!MugX.state.mirror;return MugX._ok('Mirror is '+(MugX.state.mirror?'enabled':'disabled')+' for future print copies.');};MugX.addExtraDesign=function(){try{var f=MugX._asset(['manual_psd','templates'],/\.(psd|jpg|jpeg|png)$/i,'extra design');if(!f)return MugX._ok('Extra design selection cancelled.');app.open(f);return MugX._ok('Opened '+f.name+'. Copy artwork into the print sheet and position it.');}catch(e){return MugX._fail('Extra design failed: '+e.message);}};MugX.exportJpg=function(){try{var d=MugX._doc();if(!d)return MugX._fail('Open a design first.');var f=File.saveDialog('Export JPG','*.jpg');if(!f)return MugX._ok('JPG export cancelled.');var o=new JPEGSaveOptions();o.quality=12;d.saveAs(f,o,true,Extension.LOWERCASE);return MugX._ok('JPG exported: '+f.fsName);}catch(e){return MugX._fail('JPG export failed: '+e.message);}};
'MugX repository-assets host loaded.';
